/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Atlas: typeof import('./src/components/AtlasesViews/Atlases/Atlas.vue')['default']
    AtlasCard: typeof import('./src/components/AtlasesViews/Atlases/AtlasCard.vue')['default']
    Atlases: typeof import('./src/components/AtlasesViews/Atlases/Atlases.vue')['default']
    ClickMenu: typeof import('./src/components/AtlasesViews/Atlases/ClickMenu.vue')['default']
    Default: typeof import('./src/components/AtlasesViews/Atlases/Default.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Menu: typeof import('./src/components/Header/Menu.vue')['default']
    NAnchor: typeof import('naive-ui')['NAnchor']
    NAnchorLink: typeof import('naive-ui')['NAnchorLink']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NFlex: typeof import('naive-ui')['NFlex']
    NH1: typeof import('naive-ui')['NH1']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NPopover: typeof import('naive-ui')['NPopover']
    NPopselect: typeof import('naive-ui')['NPopselect']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NSwitch: typeof import('naive-ui')['NSwitch']
    Options: typeof import('./src/components/AtlasesViews/Sider/Options.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/AtlasesViews/Sider/Search.vue')['default']
    SearchBar: typeof import('./src/components/AtlasesViews/Sider/SearchBar.vue')['default']
    Sider: typeof import('./src/components/AtlasesViews/Sider.vue')['default']
    SourceList: typeof import('./src/components/AtlasesViews/Sider/SourceList.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    TopMenu: typeof import('./src/components/Header/TopMenu.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
