/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddSource: typeof import('./src/components/modal/view/AddSource.vue')['default']
    AtlasCard: typeof import('./src/components/common/container/atlases-container/AtlasCard.vue')['default']
    AtlasCardList: typeof import('./src/components/common/container/atlases-container/AtlasCardList.vue')['default']
    Atlases: typeof import('./src/components/view/Atlases.vue')['default']
    ContextMenu: typeof import('./src/components/view/atlases/ContextMenu.vue')['default']
    CreateMenu: typeof import('./src/components/view/sider/CreateMenu.vue')['default']
    DefaultPage: typeof import('./src/components/view/atlases/DefaultPage.vue')['default']
    ImageList: typeof import('./src/components/common/ImageList.vue')['default']
    LoadingSpin: typeof import('./src/components/common/LoadingSpin.vue')['default']
    MessageBox: typeof import('./src/components/common/MessageBox.vue')['default']
    Navbar: typeof import('./src/components/app/Navbar.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDivider: typeof import('naive-ui')['NDivider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NFlex: typeof import('naive-ui')['NFlex']
    NFloatButton: typeof import('naive-ui')['NFloatButton']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NH1: typeof import('naive-ui')['NH1']
    NIcon: typeof import('naive-ui')['NIcon']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NModalProvider: typeof import('naive-ui')['NModalProvider']
    NP: typeof import('naive-ui')['NP']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpin: typeof import('naive-ui')['NSpin']
    NText: typeof import('naive-ui')['NText']
    NTree: typeof import('naive-ui')['NTree']
    NUpload: typeof import('naive-ui')['NUpload']
    NUploadDragger: typeof import('naive-ui')['NUploadDragger']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/view/sider/Search.vue')['default']
    ShowOrEdit: typeof import('./src/components/common/ShowOrEdit.vue')['default']
    Sider: typeof import('./src/components/view/Sider.vue')['default']
    SourceList: typeof import('./src/components/common/container/sources-container/SourceList.vue')['default']
    SourceSelect: typeof import('./src/components/common/select/SourceSelect.vue')['default']
    TagList: typeof import('./src/components/common/container/tag-container/TagList.vue')['default']
    TagTable: typeof import('./src/components/common/container/tag-container/TagTable.vue')['default']
    UploadedList: typeof import('./src/components/upload/UploadedList.vue')['default']
    Uploader: typeof import('./src/components/upload/Uploader.vue')['default']
    ViewAtlas: typeof import('./src/components/modal/view/ViewAtlas.vue')['default']
  }
}
