server:
  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  application:
    name: backend
  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
aliyun:
  oss:
    endpoint:
    access-key-id:
    access-key-secret:
    bucket-name: